### ISSUE TITLE
So I'm making a ban type system for a game from Discord. But.. I get this error.

### ISSUE THREAD

**Issue by Laqota** [plexidev/quick.db#251]
Here is just some example code as I'm not actually going to put my real code.

```
const ServerID = 12345

const ServerData = await db.get(ServerID)
// Error. TypeError: params.id.includes is not a function
//at arbitrate (C:\Users\Administrator\Desktop\Banning\node_modules\quick.db\src\index.js:389:32)
//at Object.get (C:\Users\Administrator\Desktop\Banning\node_modules\quick.db\src\index.js:48:16)
//at Client.<anonymous> (C:\Users\Administrator\Desktop\Banning\index.js:202:47) (ServerData Line)
```

**Comment by Zelak312** [comment]
I would love to help but you provided an example code with the error which is super great. But the error talks about a line that isn't even in the example code. Therefore, I cannot say anything than exaplain what the error says.

This error happens because you are using `.includes()` on some data that doesn't have this function. Which is why it's complaining and giving this error

**Comment by lorencerri** [comment]
Since a significant amount of time has passed without comment, I'm going to close this issue. If you have any more questions feel free to ask in our Discord!
