### ISSUE TITLE
Custom Queries

### ISSUE THREAD

**Issue by TentacleSama4254** [plexidev/quick.db#261]
it would be great if quick.db also supported custom queries for better-sqlite3

**Comment by Zelak312** [comment]
The problem with this is that the data is json stringified in the database. Which leaves not much to do with custom queries as it would only reliable colummn to use is only the ID. Unless the data is a number since it is the only one which doesn't change in it's representation but keep in mind that even though it'sa number the column would still be text.

What type of custom query you had in mind?
