### ISSUE TITLE
[Bug report] performance issues? im not sure

### ISSUE THREAD

**Issue by pendragons-code** [plexidev/quick.db#262]
![image](https://user-images.githubusercontent.com/88629349/216687027-5f643604-ab0f-4f83-9c99-2e993dde8d92.png)

I am using quick.db as the db in my [web app](https://github.com/pendragons-code/api.senghong.xyz). This web app is just a proof of concept and I just decided to throw in quick.db because it is pretty much all I needed. I have a part of the code that pushes the name of a module into the db;

Also I'm not sure since I do not write good code at all, so I apologize in advance.

```
		if(endpointsInArray === null || !endpointsInArray.includes(name)){
			await db.push("endpointsInArray", name) //pushes the thing in
			console.log(name) //is also here to tell us that the thing has reached this file
			console.log(endpointsInArray) //this line was added for testing and getting the img above
		}
```

`https://github.com/pendragons-code/api.senghong.xyz/blob/main/src/loaders/apiRoutes.js`

this could be related to me using a for in a foreach which is already dumb on my part, but I tried some other methods and I am surprised quick.db cannot seem to keep up, unless I'm wrong (I'm sorry if I am, apology in advance)

thank you - pendragon

edit: formatting

**Comment by Zelak312** [comment]
I haven't looked much at the code but just you saying you used forEach already ints at a problem. Quick.db is async, forEarch doesn't do well with async code because even if the function given to forEach is async, it will not be awaited by forEach which means that all of the calls forEach will make are executing in parallel. I am guessing that because of this you logs stuff and it doesn't show up in order or it doesn't show up. Most of the time it's because you haven't awaited the part where it's adding it to the database which makes it so the log apend before it is done.

When using async code and wanting it runned in order you cannot use forEach. A simple for loop statement and even a for of is required because for loops are affected by awaits since it doesn't dispatch functions that they are not awaitng which is the problem of forEach.

ForEach is basically a loop calling a function like so
```js
for (...) {
   callback(...)
}```
If callback is async, it will never be awaiting and unless you make your own forEarch function, it is impossible to make the original forEach await them meaning that the loop won't wait for that function to finish the execution and it will already start the next one

**Comment by pendragons-code** [comment]
Alright thank you!

**Comment by pendragons-code** [comment]
Sorry for making you review my code instead

**Comment by Zelak312** [comment]
No worries, hopefully everything works now, if not feel free to reopen the issue

**Comment by pendragons-code** [comment]
Thank you very much man!
